---
- name: Deploy langmemo to local VM
  hosts: all

  tasks:
  - name: Add Docker repository key
    become: yes
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc

  - name: Add Docker repository
    become: yes
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Install Docker
    become: yes
    package:
      name:
        - docker-ce
        - docker-ce-cli
      state: present
  - name: Start Docker
    become: yes
    systemd_service:
      name: docker
      state: started
