---
- name: Deploy langmemo to local VM
  hosts: all
  vars_files: vars/main.yml
  become: yes

  tasks:
  - name: Add Docker repository key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc

  - name: Add Docker repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Install Docker
    package:
      name:
        - docker-ce
        - docker-ce-cli
      state: present

  - name: Start Docker
    systemd_service:
      name: docker
      state: started

  - name: Install nginx
    package:
      name: nginx
      state: present

  - name: Delete default nginx config
    file:
      dest: /etc/nginx/sites-enabled/default
      state: absent

  - name: Send nginx config file to host
    template:
      src: templates/langmemo.conf.j2
      dest: /etc/nginx/sites-available/langmemo.conf
      mode: '0644'

  - name: Create symlink for nginx config file
    file:
      src: /etc/nginx/sites-available/langmemo.conf
      dest: /etc/nginx/sites-enabled/langmemo.conf
      owner: root
      group: root
      state: link

  - name: Restart nginx
    systemd_service:
      name: nginx
      state: restarted

  - name: Make langmemo directory
    file:
      state: directory
      path: /opt/langmemo

  - name: Send .env file to host
    template:
      #src: templates/.env.j2
      src: .env.j2
      dest: /opt/langmemo/.env
      mode: '0644'

  - name: Copy docker-compose file to host
    copy:
      #src: files/docker-compose.production.yml
      src: docker-compose.production.yml
      dest: /opt/langmemo/docker-compose.yml
  
  - name: Ensure placeholder bot.env exists (needed for docker services launch)
    # bot.env file (even empty) needs to be present to start docker-compose
    copy:
      dest: /opt/langmemo/bot.env
      content: sample_text
      force: false

  - name: Start docker-compose (except for bot)
    community.docker.docker_compose_v2:
      project_src: /opt/langmemo
      services:
        - db
        - backend
        - gateway
      state: present

  - name: Create Django superuser
    community.docker.docker_compose_v2_exec:
      service: backend
      project_src: /opt/langmemo
      env:
        DJANGO_SUPERUSER_USERNAME: "{{ vars[item]['superuser_username'] }}"
        DJANGO_SUPERUSER_PASSWORD: "{{ vars[item]['superuser_password'] }}"
        DJANGO_SUPERUSER_EMAIL: "{{ vars[item]['superuser_email'] }}"
      command: python manage.py createsuperuser --noinput
    loop: 
      - admin
      - botuser
    register: su_output
    # Ignore errors when superuser already exists
    failed_when: "(result.rc is defined and result.rc != 0) and ('That имя пользователя is already taken.' not in su_output.stderr)" 

  - name: Get JWT tokens
    ansible.builtin.uri:
      method: POST
      url: "http://{{ ansible_host }}/api/auth/jwt/create"
      body_format: form-urlencoded
      body:
      - [ username, "{{ botuser['superuser_username'] }}"]
      - [ password, "{{ botuser['superuser_password'] }}"]
    register: token_output

  - name: Send bot.env file to host
    template:
      src: bot.env.j2
      dest: /opt/langmemo/bot.env
  
  - name: Start bot docker
    community.docker.docker_compose_v2:
      project_src: /opt/langmemo
      services:
        - tg_bot
      state: present
